### ISSUE TITLE
Elaborar un resumen a partir de la bolsa de palabras HU3

### ISSUE THREAD

**Issue by juanheliosg** [ScalaBot-Team/PalaBrot#22]

**Comment by juanheliosg** [comment]
Existen distintas técnicas para hacer el resumen dependiendo de la unidad del significado con la que nos quedemos. 

Si resumimos solo con las palabras nos quedamos con las palabras que tienen mayor frecuencia. Podemos combinar la frecuencai con lo que se conoce como IDF (inverse document frequency). Esto mide lo poco frecuente que es una palabra en todo el lenguaje, si una palabra es "rara" puede ser plausible que aporte mucho significado. Para ello tendríamos que meter estadísticas del castellano mediante un corpus que hay en la web.

Si resumimos con las frases o mensajes podemos hacer lo siguiente: A partir de las puntuaciones de las palabras anteriores calculamos una puntuación para las frases de manera que conforme más puntuación (más palabras frecuentes en toda la conversación) más relevante es. Finalmente tenemos que cogernos un umbral para seleccionar frases relevantes, por ejemplo si la puntuacion de la frase es mayor que 5 pues vale como resumen (aquí tendríamos que meter penalización a frases largas).

En el caso de resumir con frases/mensajes podríamos construir un índice ligero con Solr(https://solr.apache.org/) para que sea todo mucho más eficiente (de hecho podríamos prescindir de  MongoDB por que guardaríamos los propios mensajes en este índice). Sino búsqueda secuencial en las frases que vamos leyendo en memoria y listo (aunque esto es mucho más lento)

Aquí se explica todo bastante bien https://becominghuman.ai/text-summarization-in-5-steps-using-nltk-65b21e352b65

**Comment by juanheliosg** [comment]
Podemos usar incluso mejor Apache Lucene directamente en vez de Solr https://github.com/outr/lucene4s

**Comment by juanheliosg** [comment]
O en vez de Solr ElasticSearch https://github.com/sksamuel/elastic4s

**Comment by balath** [comment]
@juanheliosg 👏🏽👏🏽👏🏽

**Comment by BlancaCC** [comment]
@juanheliosg me parece muy interesante, creo que nos puede dar problemas en los siguientes aspectos: 
- Potencia excesiva, recursos...  
- Enfocada para problemas abstractos, perdemos hipótesis importantes como la temporalidad y respuestas. 
- Y lo que más me preocupa es que al escribir en mensajería existe gente que fracciona la información, por ello al resumir podemos "perder mensajes" intermedios. 

Recomendaría tener presente el documento de `design` que he añadido.
