### ISSUE TITLE
Elaborar una interfaz del bot en telegram HU3 HU4

### ISSUE THREAD

**Issue by juanheliosg** [ScalaBot-Team/PalaBrot#25]
Tenemos que elaborar los mensajes a partir de los cuales este reacciona y actúa. Por el momento necesitamos tres:
Uno para iniciar el bot.

Uno para resumir que reciba como argumento un número de mensajes

Y por último otro para borrar los mensajes recolectados.

**Comment by balath** [comment]
Y uno de ayuda también podríamos añadir, no? 
Lo hacemos por comandos? en plan:
/resumir 500 //Resume los últimos 500 mensajes
/help
/deleteAll

**Comment by balath** [comment]
Resumo aquí los comandos que hay por otros issues, y quedaría:

- /resumir 500 //Resume los últimos 500 mensajes
- /help
- /delete
   - En un chat privado, elimina todo el historial de mensajes.
   - En un grupo, a petición de un usuario o administrador, elimina el historial de sus propios mensajes
- /delete All
   - En un grupo, a petición del administrador elimina todos los mensajes del grupo
