### ISSUE TITLE
Como programador me gustaría que existiriera una forma eficaz de guardar las contraseñas  y que no se suban a github

### ISSUE THREAD

**Issue by BlancaCC** [ScalaBot-Team/PalaBrot#40]
Tenemos dos opciones (que yo conozca): 
- Variables de entorno.
-  Un fichero tipo config que las guarde y que esté escrito en el .gitignore.

Bajo mi punto de vista la más cómoda para nosotros es la segunda.

**Comment by balath** [comment]
@BlancaCC Igual hay una tercera opción, aquello de la configuración remota que dijo JJ, pero no se como será...habrá algo sencillo?

**Comment by juanheliosg** [comment]
Las dos opciones de Blanca son la misma realmente. Esto se suele usar usando un archivo .env que es el que contiene las variables de entorno en lenguajes como Python o JavaScripts. No se como se hace esto en los lenguajes de la JVM pero la idea sería la misma.

En Scala se puede hacer en el mismo sbt: https://zackonengineering.com/creating-scala-environments/ mediante plugins (lo he visto muy por encima, si le puedes echar un vistazo sergio). Se que en mill también se puede hacer cosas similares. Ya que las dos herramientas se pograman basta  con  llamar a un módulo de .sbt que metamos en el gitignore y que pongas las variables con setenv.

**Comment by balath** [comment]
@juanheliosg Leyéndolo así en diagonal me he enterado de poco 😅, luego le dedico un rato👍🏽
