### ISSUE TITLE
Elegir las tecnologías que vamos a usar.

### ISSUE THREAD

**Issue by balath** [ScalaBot-Team/PalaBrot#9]
Elegir los servicios de log y otros

**Comment by BlancaCC** [comment]
- Los log son un print en la terminal 
- Los mensajes se guardan en una bd. 
- Podemos usar mongodb en un docker para bd

**Comment by balath** [comment]
Para el logging he probado [esta](https://github.com/lightbend/scala-logging) de Ligthbend que mantienen varias librerías del ecosistema de Scala. Tiene un uso muy sencillo, en [este post](https://www.playframework.com/documentation/2.8.x/ScalaLogging) está bastante bien explicado.

**Comment by balath** [comment]
Buenos días @juanheliosg @deividVentas @BlancaCC !
Para este hito creo que solo faltaría por concretar el tema del despliegue, porque de servicio de configuración remota no hablamos nada, ¿no?. Habría que añadir al Readme:

Servicios
+ `MongoDB` en un contenedor Docker para la base de datos.
+ Usaríamos `scala-logging` como librería de logging (Esto estaría por decidir, si queremos usar un servicio externo)

No se si habría que especificar también las librerías de Scala, pero si es el caso:
+ Utilizamos `canoe` [🛶](https://github.com/augustjune/canoe) como wrapper para la API de Telegram, que a su vez está basado en `cats-effect` [😸](https://github.com/typelevel/cats-effect), que es probablemente la librería básica para orientar Scala a programación funcional "pura".

**Comment by juanheliosg** [comment]
Yo lo veo perfecto, si que incluiría la librería ya que va a ser una parte fundamental del software. A nivel de despliegue yo creo que usando docker-compose para levantar en un contenedor la BD y en otro el propio bot vamos perfectos.

**Comment by balath** [comment]
@juanheliosg Acuérdate de hacer el pull request para el issue este
